feat : ToastMessage 컴포넌트 개발
Brick-log/til_web pull request #20
Opened 2023-02-12 08:46 UTC by zerocy18

**PR Type***
 - [ ] Bug
 - [x] Feature
 - [ ] Code style update
 - [ ] Refactoring
 - [ ] Build related changes
 - [ ] CI related changes
 - [ ]  Documentation content changes
 - [ ]  Other... Please describe:

**Description**
Modal 컴포넌트 개발 PR

ToastMessage 내부를 ReactNode 로 받게 하여 외부에서 ToastMessage를 전달할 때 커스텀 할 수 있도록 처리하였고,
useToast Hooks를 이용해 사용하고자 하는 페이지 내에서 사용할 수 있도록 하였습니다.

무수한 태클 주시면 감사하겠습니다.

**Reviewers**
- [ ] @haryan248 
- [ ] @jooa7878

2023-02-14 00:26 UTC, haryan248 commented on hooks/useToast.ts
> +    toastTimer.current = timer;
토스트 메시지가 나타날때 추후에 애니메이션이 추가될텐데,
지금은 여러번 눌렀을때에 기존 타이머를 초기화 후 다시 등록해서 딱 3초만 보이게 되는 것으로 되있는데

토스트 메시지의 애니메이션이 추가 되었을때, 여러번 눌렀을때 어떤식으로 처리할지?
이부분도 나중에 고려가 필요할 것 같습니다.

2023-02-14 00:26 UTC, haryan248 commented on components/ToastMessage/style.ts
> +
현재 토스트 메시지의 position이 상위 90px로 되어있는데,
해당 위치 뒤에 컨텐츠가 있을 경우 아래 사진처럼 곂쳐서 보일경우가 생길텐데,  
이런 부분은 어떻게 처리해야 할지 얘기가 필요할 것 같습니다.
 
![image](https://user-images.githubusercontent.com/51049245/218606228-2054b62b-bc11-415b-bdf1-450678335162.png)

2023-02-14 00:38 UTC, zerocy18 commented on hooks/useToast.ts
> +    toastTimer.current = timer;
추후 추가될 애니매니션 / 다중 클릭 시 처리 방식에 대해서 아젠다에 작성해놓고 기획/디자인 팀 의견 여쭤보겠습니당~

2023-02-14 00:49 UTC, zerocy18 commented on components/ToastMessage/style.ts
> +
현재 figma 내에 컬러로 배경화면이 투명도 지정해 처리가 되어있어서
따로 배경색 지정해줄 수 있는 지도 아젠다에 작성해두겠습니다.

2023-02-21 08:27 UTC, haryan248 commented on hooks/useToast.ts
> +    toastTimer.current = timer;
토스트 메시지 여러번 눌렀을때 버그가 있는것 같아요!
사라지면서 다시 한번 나타나는 현상이 있습니다

2023-02-22 00:33 UTC, haryan248 commented on components/ToastMessage/style.ts
> +  width: 270px;
지금 보니까 position absolute 가 아닌 position fixed로 화면이 밑에더라도,
스크롤 위치에 관계없이 position fixed된 위치에서 떠야할 것 같습니다.

2023-02-22 00:42 UTC, zerocy18 commented on components/ToastMessage/style.ts
> +  width: 270px;
ㅋㅋㅋ 맞아여 어제 밤에 위에 리뷰 주신 거 보다가 develop 합쳐서 보고 아 고쳐야겠다 한 상황입니다

저,, 다 회 클릭 이슈는 계속 봐야겠습니다 ㅜㅜ

2023-03-12 15:20 UTC, jooa7878 requested changes
확인했습니다 고생하셨습니다 !

2023-03-12 15:20 UTC, jooa7878 commented on components/ToastMessage/style.ts
> +});
animation 이라는 파일을 만들어서 공통으로 관리하는 것은 어떨까요?!

2023-05-15 16:04 UTC, merged