feat : 회고 상세보기 페이지 제작
Brick-log/til_web pull request #25
Opened 2023-02-22 06:33 UTC by haryan248

## PR Type\*

- [ ] Bug
- [x] Feature
- [ ] Code style update
- [ ] Refactoring
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Description

회고 상세보기 페이지입니다.
아직 목데이터가 나오지 않아 axios를 사용하지 않고 임의의 데이터 세팅으로 무한 스크롤과 디자인 적용하였습니다.
카테고리(라디오) 버튼의 경우에도 아직 제작이 완료되지 않아 이부분도 빼고 적용하였습니다.

추가로 카드의 디자인이 디자인시스템에 적용된 것과 다른 부분이 있어서 추후 수정이 필요할 것 같습니다.

## Checklist:

- [x] PR 제목 형식을 지켰는가? 
- [x] 자신의 코드를 스스로 리뷰하였는가?
- [x] 협업자의 코드를 수정하였는가?

## Reviewers:

- [ ] @jooa7878 
- [ ] @zerocy18

2023-03-07 00:50 UTC, haryan248 reviewed
@jooa7878 
@zerocy18 
무수한 질문 받습니다.

2023-03-07 00:50 UTC, haryan248 commented on pages/_app.tsx
> +      </CommonLayout>
app.tsx에 레이아웃 컴포넌트 입혔습니다.

2023-03-07 00:50 UTC, haryan248 commented on pages/cardview.tsx
> +    >
이런식으로 레이아웃 잡는 css하나를 만들어놓고 props로 열을 어느간격으로 할지 받는걸로 했습니다.
의견 주세용

참고 사지진입니당.
![image](https://user-images.githubusercontent.com/51049245/223290498-a00db50d-e144-4b2b-9764-e6b6c56b750d.png)

2023-03-12 15:17 UTC, jooa7878 requested changes
확인했습니다 고생하셨습니다!

api 통신을 다룰 instance와 react-query, recoil 세팅에 대해서도 논의해봐야겠네용

padding 부분만 수정(혹은 논의)해주시면 머지해주셔도 괜찮을 것 같습니다!

2023-03-12 15:17 UTC, jooa7878 commented on .env.development
> +NEXT_PUBLIC_API_URL=http://
예시로 add 해주신 파일 같습니다만
카톡으로 env 내용 공유하고.gitignore에 추가해야할 것 같습니다!

2023-03-12 15:17 UTC, jooa7878 commented on styles/layout.module.ts
> +`;
이렇게 되면 고정적으로 좌우 20px을  모든 페이지에서 가져가게 될텐데
피그마와 상이한 부분이 생길 수도 있을 것 같습니다!

2023-03-12 15:17 UTC, jooa7878 commented on styles/layout.module.ts
> +  width: 100%;
좋은 아이디어인 것 같습니다! 👍🏻

2023-03-16 01:24 UTC, haryan248 commented on styles/layout.module.ts
> +`;
모바일에서는 양옆 padding이 24px 23px로 고정이라 24,23으로 수정하겠습니다.

2023-03-16 01:43 UTC, jooa7878 approved these changes
확인했습니다! 고생하셨습니다!

2023-05-05 14:39 UTC, merged