refactor : button 컴포넌트 리팩토링
Brick-log/til_web pull request #29
Opened 2023-03-10 08:56 UTC by haryan248

## PR Type\*

- [ ] Bug
- [x] Feature
- [ ] Code style update
- [ ] Refactoring
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Description

버튼 컴포넌트 PR 입니다.
버튼 컴포넌트를 아톰으로만 관리하도록 변경하였습니다.
확인완료되면 develop에 머지할게요!

## Checklist:

- [x] PR 제목 형식을 지켰는가? 
- [x] 자신의 코드를 스스로 리뷰하였는가?
- [x] 협업자의 코드를 수정하였는가?

## Reviewers:

- [ ] @jooa7878 
- [ ] @zerocy18

2023-03-25 07:40 UTC, jooa7878 requested changes
확인했습니다 고생하셨습니다 !

코멘트만 확인부탁드릴게용!

2023-03-25 07:40 UTC, jooa7878 commented on pages/test.tsx
> +  };
props를 받아서 (ex. device) MButton과 통일해서 사용할 수 있을 것 같습니다 !

2023-03-26 03:53 UTC, haryan248 commented on pages/test.tsx
> +  };
사용법 예시를 만들어놓은거라 버튼쓰는곳에서 각자 만들어서 쓰는걸로 하면 될것 같아요!

2023-04-01 01:50 UTC, zerocy18 commented
확인했습니다!

2023-04-02 13:26 UTC, jooa7878 approved these changes

2023-04-03 00:38 UTC, merged